### PR TITLE
revert to SeqAn 2.1.1 for older GCCs

### PR DESCRIPTION
**Pull request by jvolkening**
* replaced contents of `porechop/include/seqan` with v2.1.1
* modified flags in Makefile to declare C++11 support
* modified version string to reflect nature of branch

### CODE REVIEW

**Comment by rrwick** [comment]
Thanks! I'll try to keep this branch up to date - when I merge new changes into the master branch, I'll merge them into this one as well.

**Comment by jvolkening** [comment]
Thanks Ryan! This is up on [bioconda](https://bioconda.github.io/recipes/porechop/README.html) now but still points to my fork. If you can create a tag from the C++11 branch I will update the bioconda recipe to point to the "official" repo.

**Comment by rrwick** [comment]
Okay, here's a new tag:
https://github.com/rrwick/Porechop/releases/tag/v0.2.3-C%2B%2B11

**Comment by sjackman** [comment]
The `v0.2.3-C++11` I'm guessing uses C++11.
What version of C++ does `v0.2.3` use?

**Pull request merged**
